[package]
name = "osteserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser="3.0.0"
httparse="1.7.1"
url="2.2.2"